### Магазины
### Получение всех магазинов

GET http://127.0.0.1:8000/api/v1/list/shops/

### Создание магазина

POST http://127.0.0.1:8000/api/v1/list/shops/
Content-Type: application/json

{
    "name": "Магазин №3"
}

### Получение конкретного магазина

GET http://127.0.0.1:8000/api/v1/shop/4/

### Изменение магазина

PUT http://127.0.0.1:8000/api/v1/shop/4/
Content-Type: application/json

{
    "name": "Больше не магазин))))"
}

### Удаление магазина

DELETE http://127.0.0.1:8000/api/v1/shop/4/

### Продукты
### Получение всех продуктов

GET http://127.0.0.1:8000/api/v1/list/products/

### Создание продукта

POST http://127.0.0.1:8000/api/v1/list/products/
Content-Type: application/json

{
    "name": "Продукт а чо",
    "content": "Самый крутой продукт в мире!!",
    "shop": 3
}

### Получение конкретного продукта

GET http://127.0.0.1:8000/api/v1/product/3/

### Изменение продукта

PUT http://127.0.0.1:8000/api/v1/product/3/
Content-Type: application/json

{
    "name": "Продукт без а чо",
    "content": "Продукт крутой рил",
    "shop": 3
}

### Удаление продукта

DELETE http://127.0.0.1:8000/api/v1/product/3/

