### Магазины
### Получение всех магазинов

GET http://127.0.0.1:8000/api/v1/shop/

### Создание магазина

POST http://127.0.0.1:8000/api/v1/shop/
Content-Type: application/json

{
    "name": "Магазин №821"
}

### Получение конкретного магазина

GET http://127.0.0.1:8000/api/v1/shop/8/
Authorization: Token d172177844b4f12e4ad651f7b5fe80d3385f9304


### Изменение магазина

PUT http://127.0.0.1:8000/api/v1/shop/8/
Content-Type: application/json

{
    "name": "Больше не магазинчик)))))"
}

### Удаление магазина

DELETE http://127.0.0.1:8000/api/v1/shop/2/

### Продукты
### Получение всех продуктов

GET http://127.0.0.1:8000/api/v1/product/?page=2&page_size=2

### Создание продукта

POST http://127.0.0.1:8000/api/v1/product/
Content-Type: application/json
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkzMzIzNTQwLCJpYXQiOjE2OTMzMjMyNDAsImp0aSI6Ijg3ZDc3NjJkMDlhZjRhZGI5NTFmZDUxYWQ4NjAyNThmIiwidXNlcl9pZCI6M30.2pMzLgK2IlqbstNsaP2lHMw8Kctb4_GB4dC1DKJJHhw

{
    "name": "Продуктfsdfdsfs",
    "content": "Самый крутой продукт в мире!!",
    "shop": 3
}

### Получение конкретного продукта
  
GET http://127.0.0.1:8000/api/v1/product/8/
Authorization: JWT eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjkyNTI1NTAxLCJpYXQiOjE2OTI1MjUyMDEsImp0aSI6ImExYWIxM2U1ZTkxODQ4NDk4OGMxYTVkMGJlN2NiMjgzIiwidXNlcl9pZCI6M30.bEY6nph8Qm7U4_ynQDEuel1krBnZLByT21JipQkggkk

###

PUT http://127.0.0.1:8000/api/v1/product/8/
Content-Type: application/json
Authorization: Token cf1ab8fde87c45db6b65748ec1d51f972e47320d

{
    "name": "Продукт без а чо",
    "content": "Продукт крутой рил",
    "shop": 3
}

### Удаление продукта

DELETE http://127.0.0.1:8000/api/v1/product/delete/5/
Authorization: Token cf1ab8fde87c45db6b65748ec1d51f972e47320d

###

POST http://127.0.0.1:8000/api/v1/auth/users/
Content-Type: application/json

{
    "username": "root12",
    "password": "vanekkkkkk"
}

### Получение токенов

POST http://127.0.0.1:8000/api/v1/token/
Content-Type: application/json

{
    "username": "root12",
    "password": "vanekkkkkk"
}
###

POST http://127.0.0.1:8000/auth/token/login/
Content-Type: application/json

{
    "username": "root12",
    "password": "vanekkkkkk"
}

###

POST http://127.0.0.1:8000/auth/token/logout/
Content-Type: application/json
Authorization: Token d2fb8d45196b2769ed0b1fd00b113dbedbd412a9
